#!/bin/sh
sync
/etc/init.d/network stop &
pid=$!
umount -f /boot 2>/dev/null
cd /mnt
DIRS=$(ls)
for dir in $DIRS;do
        umount -f $dir 2>/dev/null
done
sync
wait $pid
echo 'b' > /proc/sysrq-trigger
