#!/bin/sh
#
# Copyright (C) 2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

ucidef_set_led_default "work" "WORK" "blue:work" "1"
ucidef_set_led_netdev "lan" "LAN" "blue:net" "eth0"

board_config_flush

exit 0
