#!/bin/sh
#
# Copyright (C) 2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

ucidef_set_led_netdev "wan" "WAN" "blue:net" "eth3"
ucidef_set_led_netdev "lan" "LAN" "amber:sata" "br-lan"
ucidef_set_led_default "work" "WORK" "green:work" "1"

board_config_flush

exit 0
