name: 'Package OpenWrt firmware for Armvirt targets'
author: 'ophub'
description: 'Package Armvirt rootfs into OpenWrt firmware images. Supports Allwinner, Rockchip, and Amlogic S9xxx series devices.'
inputs:
  mode:
    description: 'Select the packaging script to use.'
    required: false
    default: 'flippy'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd "${GITHUB_ACTION_PATH}"
        ./openwrt_flippy.sh
      
branding:
  icon: 'terminal'
  color: 'gray-dark'
