#!/bin/sh
#
# Copyright (C) 2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

ucidef_set_led_netdev "lan" "LAN" "yellow:lan" "eth0"
ucidef_set_led_netdev "wan" "WAN" "yellow:wan" "eth1"

board_config_flush

exit 0
