#!/bin/sh
#
# Copyright (C) 2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

ucidef_set_led_default "work" "WORK" "led_green" "1"
ucidef_set_led_netdev "wan" "WAN" "led_amber" "eth0"
ucidef_set_led_netdev "lan" "LAN" "led_blue" "eth1"

board_config_flush

exit 0
